### PR TITLE
Add environment variable handling to Google Pay

### LINKED ISSUE #566: Google Pay Missing Environment Variable
The Google Pay JavaScript file is missing the `environment` configuration. All requests are being being against the test environment and doesn't let a merchant choose to move to production for Google Pay.

https://developers.google.com/pay/api/web/reference/client#PaymentsClient

https://developers.google.com/pay/api/web/reference/request-objects#PaymentOptions

### PR DESCRIPTION
**Pull request by nikolas4175-godaddy**
# Summary
This PR adds handling for passing the appropriate Environment variable (i.e. `PRODUCTION` or `TEST`) when setting up the Google Pay JS client for gateways that implement the Google Pay Frontend class. Previously no environment variable was passed, which will cause txns to default to TEST according to the [Google Pay docs](https://developers.google.com/pay/api/web/reference/request-objects#PaymentOptions). 

## Acceptance Criteria
 - [x] Appropriate environment variable is passed according to plugin settings
 - [ ] Able to process txns in both Prod and Test envs

### CODE REVIEW

**Comment by ragulka** [comment]
@nikolas4175-godaddy I cherry-picked the FW version number changes to the [release/5.11.7](https://github.com/godaddy-wordpress/wc-plugin-framework/tree/release/5.11.7) branch, so that we can PR other fixes and changes to the release. I've also adjusted the base branch here so your PR gets merged into the release branch first.

**Comment by unfulvio-godaddy** [comment]
@nikolas4175-godaddy @ragulka this branch has been rebased to use #611  (5.11.8 release branch) since we have tagged v5.11.7

**Comment by nikolas4175-godaddy** [comment]
Discussed in Slack ([thread](https://godaddy.slack.com/archives/C01NH3P7FGB/p1692686561059139)), but for clarity: It seems that more changes are needed at the plugin (and possibly also FW) level to get Google Pay txns working in Prod (AC2 above), but the change in this PR is certainly a part of that and meets AC1 so I'll move this out of draft to prevent further blockers or rebasing work while we sort this out.

**Review by itambek-godaddy — APPROVED** [review]
LGTM

**Pull request merged**
